#include "menu.h"
#include "tasks.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define MINN 1
#define MAXN 20
#define MINCHOICE 0
#define MAXROT 1
#define MAXDIR 3

void print_menu(void) {
  printf("\n-----------------\n");
  printf("  SPIRALS\n");
  printf("-----------------\n");
  printf("0 - Guide me\n");
  printf("1 - Make it\n");
  printf("2 - Save it\n");
  printf("3 - Load it\n");
  printf("4 - Print it\n");
  printf("5 - Exit\n");
  printf(">> ");
}

int str_to_dir(char *str) {
  switch (str[0]) {
  case 'l':
    return 0;
  case 'r':
    return 1;
  case 'u':
    return 2;
  case 'd':
    return 3;
  default:
    return -1;
  }
}

int *choose(int *n, int c, int *mat, int *dir, int *rot) {
  switch (c) {
  case 0:
    printf("Guide me (0) : Gives an explanation for what each menu item does.\n");
    printf("Make it (1) : Makes a matrix the way the user specifies it.\n");
    printf("Save it (2) : Saves the matrix.\n");
    printf("Load it (3) : Loads a matrix from a file, which was previously generated by the program.\n");
    printf("Print it (4) : Prints the matrix that is currently in memory.\n") ;
    printf("Exit (5) : Exits the program\n");
    return mat;
  case 1:
    printf("How big do you want it?(1-20)");
    scanf("%d", n);
    if (*n < MINN || *n > MAXN) {
      printf("N must be between 1 and 20\n");
      return mat;
    }
    printf(
        "\nWhich direction should it flow? (0-Left, 1-Right, 2-Up, 3-Down) ");
    scanf("%d", dir);
    if (*dir < MINCHOICE || *dir > MAXDIR) {
      printf("Direction must be between 0 and 3\n");
      return mat;
    }
    printf("\ncw(0) or ccw(1)");
    scanf("%d", rot);
    if (*rot < MINCHOICE || *rot > MAXROT) {
        printf("Rotation must be 0 or 1\n");
      return mat;
    }
    printf("Generating matrix...");

    return generate_matrix(*n, mat, *dir, *rot);
  case 2:
    printf("Saving matrix...");
    int ret = save_mat(*n, mat, *dir, *rot);
    ret == -1 ? printf("\n") : printf("Successful save\n");
    return mat;
  case 3:
    printf("What is the path of the file?\n");
    char *filename = (char *)malloc(256); // elvileg max path length Windowson
    int res = scanf("%s", filename);
    if (res == 0 || filename == NULL)
      return mat;
    char *tmp = strdup(filename);
    FILE *f = fopen(filename, "r");
    if (f == NULL) {
      printf("couldnt open file\n");
      return mat;
    }
    tmp = strtok(tmp, "_");
    *n = atoi(strtok(NULL, "_"));
    *dir = str_to_dir(strtok(NULL, "_"));
    *rot = strcmp(strtok(NULL, "_"), "cw") == 0 ? 0 : 1;
    free(filename);
    free(tmp);
    return load_mat(mat, *n, f);
  case 4:
    print_matrix(*n, mat);
    return mat;
  default:
    return mat;
  }
}
